name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: "none"

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  lottie: ^3.0.0
  envied: ^0.5.3
  equatable: ^2.0.5
  # flutter_gen: ^5.4.0
  flutter_svg: ^2.0.9
  uuid: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0



flutter_gen:
  output: lib/src/asset/
  line_length: 80 

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/color/
    - assets/icons/
    - assets/lottie/


uses-material-design: true    

  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Italic.ttf
  #         style: italic