name: architecture_template
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#Core Dependencies
  easy_localization: ^3.0.3

# State
  flutter_bloc: ^8.1.3


#Config
  equatable: ^2.0.5
  formz: ^0.6.1


# utility
  logger: ^2.0.2+1
  easy_logger: ^0.0.2
  kartal: ^3.5.0
  google_fonts: ^6.1.0

# Router
  auto_route: ^7.8.4 


#dependency_overrides:
# cupertino_icons: ^1.0.1


# Modules
  gen:
    path: module/gen

  common:
    path: module/common

  core:
    path: module/core

  widgets:
    path: module/widgets

  repository:
    path: module/repository  

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.1.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.3


flutter:
  uses-material-design: true

  assets:
    - asset/translations/
