name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^4.0.0-dev.2
  shared_preferences: ^2.2.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
